# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_auto_20160314_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Blog'),
        ),
    ]
