# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 18:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20160314_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='seq',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
