# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_blog_seq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.Paragraph'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('comment', 'paragraph')]),
        ),
    ]
